### ISSUE TITLE
windows: `no nifs found` compilation failures when running tests

### ISSUE THREAD

**Issue by simonmcconnell** [E-xyza/zigler#267]
If I try to test a file or simply run `mix test`, it will give a compilation error one of the test files.  You can keep trying and get a different file most times (due to the parallel compiler).

```
❯ mix test .\test\support\zigtest\passing_tests.ex
Compiling 35 files (.ex)

11:45:29.921 [warn]  windows is not supported, but may work.

If you find an error in the process, please leave an issue at:
https://github.com/ityonemo/zigler/issues


11:45:29.928 [warn]  windows is not supported, but may work.

If you find an error in the process, please leave an issue at:
https://github.com/ityonemo/zigler/issues


11:45:29.935 [warn]  windows is not supported, but may work.

If you find an error in the process, please leave an issue at:
https://github.com/ityonemo/zigler/issues


11:45:29.942 [warn]  windows is not supported, but may work.

If you find an error in the process, please leave an issue at:
https://github.com/ityonemo/zigler/issues


11:45:29.950 [warn]  windows is not supported, but may work.

If you find an error in the process, please leave an issue at:
https://github.com/ityonemo/zigler/issues


== Compilation error in file test/support/zigtest/documentation.ex ==  
** (CompileError) test/support/zigtest/documentation.ex: no nifs found 
in the module Elixir.ZiglerTest.Integration.Documentation
    expanding macro: Zig.Compiler.__before_compile__/1
    test/support/zigtest/documentation.ex:1: ZiglerTest.Integration.Documentation (module)
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

again

```
❯ mix test .\test\support\zigtest\passing_tests.ex
Compiling 35 files (.ex)

...

== Compilation error in file test/support/zigtest/failing_test.ex ==
** (CompileError) test/support/zigtest/failing_test.ex: no nifs found in the module Elixir.ZiglerTest.ZigTest.FailingTest
    expanding macro: Zig.Compiler.__before_compile__/1 
    test/support/zigtest/failing_test.ex:1: ZiglerTest.ZigTest.FailingTest (module)
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

again

```
❯ mix test .\test\support\zigtest\passing_tests.ex
Compiling 35 files (.ex)

...

== Compilation error in file test/support/types.ex ==  
** (CompileError) test/support/types.ex: no nifs found 
in the module Elixir.ZiglerTest.Types
    expanding macro: Zig.Compiler.__before_compile__/1 
    test/support/types.ex:1: ZiglerTest.Types (module) 
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by simonmcconnell** [comment]
It is because the parser does not handle CRLF, just LF.  As a quick and dirty workaround I added the below to `Parser.parse()`.  I'll try update the parser to handle both line endings.

```elixir
code =
  if :os.type() |> elem(0) == :win32 do
    String.replace(code, "\r\n", "\n")
  else
    code
  end
```

I got this error after that change.

```
== Compilation error in file test/support/zigtest/passing_tests.ex ==
** (CompileError)  this zig compiler warning hasn't been incorporated into the parser.
Please file a report at:
https://github.com/ityonemo/zigler/issues
Assertion failed at /home/andy/dev/bootstrap-zig/zig/src/stage1/analyze.cpp:8061 in get_builtin_value. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped

    lib/zig/parser/error.ex:54: Zig.Parser.Error.parse/2
    lib/zig/command.ex:36: Zig.Command.compile/2
    lib/zig/compiler.ex:103: Zig.Compiler.compilation/2
    expanding macro: Zig.Compiler.__before_compile__/1
    test/support/zigtest/passing_tests.ex:1: ZiglerTest.ZigTest.PassingTests (module)
```

and then the LLVM error, which should be fixed in 0.8.0 🤷 

```
== Compilation error in file test/support/zigtest/transitive.ex ==
** (CompileError)  this zig compiler warning hasn't been incorporated into the parser.
Please file a report at:
https://github.com/ityonemo/zigler/issues
LLVM ERROR: Bad $ operand number in inline asm string: ' movl %fs:0x18, $104801965141131264'

    lib/zig/parser/error.ex:54: Zig.Parser.Error.parse/2
    lib/zig/command.ex:36: Zig.Command.compile/2
    lib/zig/compiler.ex:102: Zig.Compiler.compilation/2
    expanding macro: Zig.Compiler.__before_compile__/1
    test/support/zigtest/transitive.ex:1: ZiglerTest.ZigTest.Transitive (module)
```

**Comment by ityonemo** [comment]
oh wow cool, thanks for the catch.  As it turns out cr/lf is prohibited in zig code itself, so I'll have to process that anyways.  are you by chance on windows?

**Comment by simonmcconnell** [comment]
I am. 

I think we might need to upgrade to 0.8.0 to get us past the next error though.

**Comment by ityonemo** [comment]
after that, if you look at erl_nif.h there are some things that are "windows" only, for example this line:

```
memcpy(&WinDynNifCallbacks,callbacks,sizeof(TWinDynNifCallbacks))
```
which will need to be implemented in zig.

**Comment by ityonemo** [comment]
ok I'm playing around with it, 0.8.1 might support windows, gonna give one shot at testing it manually, but otherwise going to YOLO it through CI, I'll tag you if you want to take a gander at it.

**Comment by simonmcconnell** [comment]
Well we get a new error now 😃 

```
❯ mix test
Compiling 34 files (.ex)

14:24:58.138 [warn]  windows is not supported, but may work.  

If you find an error in the process, please leave an issue at:
https://github.com/ityonemo/zigler/issues


14:24:58.111 [warn]  windows is not supported, but may work.  

If you find an error in the process, please leave an issue at:
https://github.com/ityonemo/zigler/issues


14:24:58.124 [warn]  windows is not supported, but may work.  

If you find an error in the process, please leave an issue at:
https://github.com/ityonemo/zigler/issues


14:24:58.131 [warn]  windows is not supported, but may work.

If you find an error in the process, please leave an issue at:
https://github.com/ityonemo/zigler/issues


14:24:58.118 [warn]  windows is not supported, but may work.

If you find an error in the process, please leave an issue at:
https://github.com/ityonemo/zigler/issues


14:24:58.213 [debug] compiling nif for module ZiglerTest.ZigTest.FailingTest in path C:/Users/simon/AppData/Local/Temp/.zigler_compiler/test/Elixir.ZiglerTest.ZigTest.FailingTest

14:24:58.213 [debug] compiling nif for module ZiglerTest.ZigTest.PassingTests in path C:/Users/simon/AppData/Local/Temp/.zigler_compiler/test/Elixir.ZiglerTest.ZigTest.PassingTests

14:24:58.247 [debug] copied c:/Users/simon/code/zigler/test/support/zigtest/imported.zig to c:/Users/simon/AppData/Local/Temp/.zigler_compiler/test/Elixir.ZiglerTest.ZigTest.Transitive/imported.zig

14:24:58.250 [debug] copied c:/Users/simon/code/zigler/test/support/zigtest/namespaced.zig to c:/Users/simon/AppData/Local/Temp/.zigler_compiler/test/Elixir.ZiglerTest.ZigTest.Transitive/namespaced.zig

14:24:58.253 [debug] copied c:/Users/simon/code/zigler/test/support/zigtest/nonpublic.zig to c:/Users/simon/AppData/Local/Temp/.zigler_compiler/test/Elixir.ZiglerTest.ZigTest.Transitive/nonpublic.zig

14:24:58.253 [debug] compiling nif for module ZiglerTest.ZigTest.Transitive in path C:/Users/simon/AppData/Local/Temp/.zigler_compiler/test/Elixir.ZiglerTest.ZigTest.Transitive

14:24:58.328 [debug] wrote build.zig to C:/Users/simon/AppData/Local/Temp/.zigler_compiler/test/Elixir.ZiglerTest.ZigTest.Transitive/build.zig

14:24:58.329 [debug] wrote build.zig to C:/Users/simon/AppData/Local/Temp/.zigler_compiler/test/Elixir.ZiglerTest.ZigTest.PassingTests/build.zig

14:24:58.331 [debug] wrote build.zig to C:/Users/simon/AppData/Local/Temp/.zigler_compiler/test/Elixir.ZiglerTest.ZigTest.FailingTest/build.zig

== Compilation error in file test/support/zigtest/transitive.ex ==
** (CompileError)  this zig compiler warning hasn't been incorporated into the parser.
Please file a report at:
https://github.com/ityonemo/zigler/issues
C:\Users\simon\code\zigler\zig\zig-windows-i386-0.8.1\lib\std\builtin.zig:13:28: error: container 'builtin' has no member called 'is_test'
pub const is_test = builtin.is_test;
                           ^
C:\Users\simon\code\zigler\zig\zig-windows-i386-0.8.1\lib\std\special\compiler_rt.zig:8:24: note: referenced here
const is_test = builtin.is_test;
                       ^
C:\Users\simon\code\zigler\zig\zig-windows-i386-0.8.1\lib\std\special\compiler_rt.zig:17:25: note: referenced here
    const linkage = if (is_test) builtin.GlobalLinkage.Internal else builtin.GlobalLinkage.Weak;
                        ^
C:\Users\simon\code\zigler\zig\zig-windows-i386-0.8.1\lib\std\builtin.zig:18:27: error: container 'builtin' has no member called 'target'
pub const target = builtin.target;
                          ^
C:\Users\simon\code\zigler\zig\zig-windows-i386-0.8.1\lib\std\target.zig:1251:32: note: referenced here
    pub const current = builtin.target;
                               ^
C:\Users\simon\code\zigler\zig\zig-windows-i386-0.8.1\lib\std\special\compiler_rt\atomics.zig:8:24: note: referenced here
const arch = std.Target.current.cpu.arch;
                       ^
C:\Users\simon\code\zigler\zig\zig-windows-i386-0.8.1\lib\std\special\compiler_rt\atomics.zig:17:37: note: referenced here
const supports_atomic_ops = switch (arch) {
                                    ^
C:\Users\simon\code\zigler\zig\zig-windows-i386-0.8.1\lib\std\special\compiler_rt\atomics.zig:123:9: note: referenced here
    if (supports_atomic_ops) {
        ^
C:\Users\simon\code\zigler\zig\zig-windows-i386-0.8.1\lib\std\start.zig:30:16: error: container 'builtin' has no member called 'zig_is_stage2'
    if (builtin.zig_is_stage2) {
               ^

    lib/zig/parser/error.ex:54: Zig.Parser.Error.parse/2
    lib/zig/command.ex:30: Zig.Command.compile/2
    lib/zig/compiler.ex:99: Zig.Compiler.compilation/2
    expanding macro: Zig.Compiler.__before_compile__/1
    test/support/zigtest/transitive.ex:1: ZiglerTest.ZigTest.Transitive (module)
```

**Comment by simonmcconnell** [comment]
unhandled zig compiler warnings are due to the error parser failing on Windows paths, as they have `:` in them and then `find_file` fails as they don't start with `/`.
