### ISSUE TITLE
Troubles using external libs

### ISSUE THREAD

**Issue by munjalpatel** [E-xyza/zigler#421]
Hey Isaac (@ityonemo) great work with Zigler. I am looking forward to using it in my projects.

I am having some troubles getting an external library to work and was wondering if you could help.
_(Link to repo with reproducible code: https://github.com/munjalpatel/exzig)_

Here is what I am trying to do:
```
Go code --> shared lib (.h and .so) --> Elixir (using Zigler)
```

Here is the error I am getting when try to run `iex -S mix`:
```
Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] [dtrace]

Compiling 2 files (.ex)

15:04:24.143 [debug] running command: /Users/munjalapatel/workspace/playground/elixir-learning/exzig/deps/zigler/zig/zig-macos-x86_64-0.10.1/zig fmt /var/folders/zv/ypxkdwcx46d9vrf40tckqq880000gn/T/Elixir.Greeter/build.zig

15:04:24.424 [debug] wrote build.zig to /var/folders/zv/ypxkdwcx46d9vrf40tckqq880000gn/T/Elixir.Greeter/build.zig

15:04:24.427 [debug] running command: /Users/munjalapatel/workspace/playground/elixir-learning/exzig/deps/zigler/zig/zig-macos-x86_64-0.10.1/zig run /Users/munjalapatel/workspace/playground/elixir-learning/exzig/_build/dev/lib/zigler/priv/beam/sema.zig --pkg-begin analyte /Users/munjalapatel/workspace/playground/elixir-learning/exzig/lib/.Elixir.Greeter.zig --pkg-begin beam /Users/munjalapatel/workspace/playground/elixir-learning/exzig/_build/dev/lib/zigler/priv/beam/beam.zig --pkg-begin sema /Users/munjalapatel/workspace/playground/elixir-learning/exzig/_build/dev/lib/zigler/priv/beam/sema/on.zig --pkg-end --pkg-begin erl_nif /Users/munjalapatel/workspace/playground/elixir-learning/exzig/_build/dev/lib/zigler/priv/beam/erl_nif.zig --pkg-end --pkg-end --pkg-begin erl_nif /Users/munjalapatel/workspace/playground/elixir-learning/exzig/_build/dev/lib/zigler/priv/beam/erl_nif.zig --pkg-end --pkg-begin sema /Users/munjalapatel/workspace/playground/elixir-learning/exzig/_build/dev/lib/zigler/priv/beam/sema/on.zig --pkg-end --pkg-end --pkg-begin sema /Users/munjalapatel/workspace/playground/elixir-learning/exzig/_build/dev/lib/zigler/priv/beam/sema/on.zig --pkg-end -lc

== Compilation error in file lib/greeter.ex ==
** (MatchError) no match of right hand side value: ["error(link): undefined reference to symbol '_Greet'\nerror(link):   first referenced in '/Users/munjalapatel/.cache/zig/o/0e040908f395283c64be94201a6a73b1/sema.o'"]
    (zigler 0.10.3) lib/zig/compile_error.ex:11: Zig.CompileError.to_error/2
    (zigler 0.10.3) lib/zig/sema.ex:88: Zig.Sema.run_sema!/3
    (zigler 0.10.3) lib/zig/compiler.ex:84: Zig.Compiler.compile/4
    (zigler 0.10.3) expanding macro: Zig.Compiler.__before_compile__/1
    lib/greeter.ex:1: Greeter (module)
```

I verified that the compiled `.so` has the `Greet` in the dynamic symbol table.
Here is the output of `nm greeter.so | grep "Greet"`
```

0000000000093f40 T _Greet
0000000000093ec0 t __cgoexp_d7fc1fbdb657_Greet
0000000000093e20 t _main.Greet
```

I also created a small tester in `C` to ensure the compiled code works as expected.
```C
#include "greeter.h"
#include <stdio.h>

// Build using: gcc -o test_greeter test_greeter.c ./greeter.so
// Run test: ./test_greeter

int main()
{
  char *greeting = Greet("Munjal");
  printf("%s", greeting);

  return 0;
}
```

The output of `gcc -o test_greeter test_greeter.c ./greeter.so && ./test_greeter`
```
Hello, Munjal!
```

---

Here is my setup:

**lib/greeter/src/main.go**
```go
package main

// Build using: go build -buildmode=c-shared -o greeter.so ./src/...

// #include <stdio.h>
// #include <stdlib.h>
import "C"
import "fmt"

//export Greet
func Greet(name *C.char) *C.char {
    return C.CString(fmt.Sprintf("Hello, %s!\n", C.GoString(name)))
}

func main() {}
```

**lib/greeter.ex**
```ex
defmodule Greeter do
  use Zig,
    otp_app: :exzig,
    link_lib:
      "/Users/munjalapatel/workspace/playground/elixir-learning/exzig/lib/greeter/greeter.so"

  ~Z"""
  const beam = @import("beam");

  const greeter = @cImport({
    @cInclude("/Users/munjalapatel/workspace/playground/elixir-learning/exzig/lib/greeter/greeter.h");
  });

  pub fn greet(env: beam.env, name: []u8) beam.term {
    return beam.make(env, .{.ok, greeter.Greet(@as([*c]u8, &name[0]),)}, .{});
  }
  """
end
```

**lib/exzig.ex**
```ex
defmodule Exzig do
  def greet(name) do
    Greeter.greet(name)
  end
end
```

**Comment by ityonemo** [comment]
error says "undefined reference to _Greet" I would have expected it to say "undefined reference to Greet"  Is there something going on with the underscore?

**Comment by ityonemo** [comment]
closed.  supporting go cross-compilation is not a priority for zigler.
