### ISSUE TITLE
could not list directory "guides": no such file or directory

### ISSUE THREAD

**Issue by dvic** [E-xyza/zigler#482]
Tried 0.13.0 out in a demo app, but I get this: 

```
==> zigler_demo
Error while loading project :zigler at /Users/dvic/Development/temp/zigler_demo/deps/zigler
** (File.Error) could not list directory "guides": no such file or directory
    (elixir 1.17.2) lib/file.ex:1700: File.ls!/1
    /Users/dvic/Development/temp/zigler_demo/deps/zigler/mix.exs:50: Zigler.MixProject.guides/0
    /Users/dvic/Development/temp/zigler_demo/deps/zigler/mix.exs:42: Zigler.MixProject.docs/0
    /Users/dvic/Development/temp/zigler_demo/deps/zigler/mix.exs:30: Zigler.MixProject.project/0
    (mix 1.17.2) lib/mix/project.ex:943: Mix.Project.get_project_config/1
    (mix 1.17.2) lib/mix/project.ex:205: Mix.Project.push_config/2
    (mix 1.17.2) lib/mix/project.ex:168: Mix.Project.push/3
```

I guess the guides should also be included in the published package?

Awesome work by the way, getting this release done 👍

**Comment by ityonemo** [comment]
oh yikes!  good catch, thanks!
