### ISSUE TITLE
Can't download with `zig.get`

### ISSUE THREAD

**Issue by monotykamary** [E-xyza/zigler#490]
When running zig.get on MacOS
```
mix zig.get --version 0.13.0 --os macos
```

I encounter this error:
```
** (FunctionClauseError) no function clause matching in String.trim/1    
    
    The following arguments were given to String.trim/1:
    
        # 1
        nil
    
    Attempted function clauses (showing 1 out of 1):
    
        def trim(string) when is_binary(string)
    
    (elixir 1.17.2) lib/string.ex:1304: String.trim/1
    mix.tasks/zig.get.ex:175: Mix.Tasks.Zig.Get.get_public_key/1
    mix.tasks/zig.get.ex:49: Mix.Tasks.Zig.Get.run/1
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
```

**Comment by monotykamary** [comment]
Not an actualy blocker, since at least zigler is smart enough to find the system `zig`.

**Comment by ityonemo** [comment]
thanks for the bug report.

**Comment by ityonemo** [comment]
are you using zigler 0.13.{1,2}?  I don't see a get_public_key function in the new mix zig.get

**Comment by monotykamary** [comment]
yep, I just got the latest version and tried to run it from that

**Comment by ityonemo** [comment]
https://preview.hex.pm/preview/zig_get/0.13.1/show/mix.tasks/zig.get.ex

try `mix deps.update zig_get`

**Comment by monotykamary** [comment]
hmm mostly the same - I have removed `deps` and `_build` a few times, but nothing different on that front either

```
$ mix deps.update zig_get
Resolving Hex dependencies...
Resolution completed in 0.018s
Unchanged:
  jason 1.4.4
  nimble_parsec 1.4.0
  pegasus 0.2.5
  protoss 0.2.1
  zig_get 0.13.1
  zig_parser 0.4.0
  zigler 0.13.2
```

```
$ mix zig.get --version 0.13.0 --os macos
** (FunctionClauseError) no function clause matching in String.trim/1    
    
    The following arguments were given to String.trim/1:
    
        # 1
        nil
    
    Attempted function clauses (showing 1 out of 1):
    
        def trim(string) when is_binary(string)
    
    (elixir 1.17.2) lib/string.ex:1304: String.trim/1
    mix.tasks/zig.get.ex:175: Mix.Tasks.Zig.Get.get_public_key/1
    mix.tasks/zig.get.ex:49: Mix.Tasks.Zig.Get.run/1
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
 ```

**Comment by ityonemo** [comment]
The zig_get infrastructure has changed, so I will close this issue.
